# Generated by Django 5.1.1 on 2025-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failedloginattempt",
            name="username",
        ),
        migrations.AddField(
            model_name="failedloginattempt",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
