# Generated by Django 5.1.1 on 2025-04-01 15:18

from django.db import migrations
from django.conf import settings


def create_demo_user(apps, schema_editor):
    """Create or update the demo user account for easy testing"""
    from authentication.utils import setup_demo_user
    
    user, created = setup_demo_user()
    status = "created" if created else "updated"
    print(f"Demo user {status} successfully with email: demo@twitterclone.com")


def reverse_func(apps, schema_editor):
    """This migration is reversible but doesn't need to do anything on reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_failedloginattempt_username_and_more"),
        ("users", "0003_user_last_activation"),
    ]

    operations = [
        migrations.RunPython(create_demo_user, reverse_func),
    ]
