# Generated by Django 5.1.1 on 2025-03-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_tweet_comments_count_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="media_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CommentMediaAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="comment_media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tweets.comment",
                    ),
                ),
            ],
        ),
    ]
