# Generated by Django 5.1.1 on 2025-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
