# Generated by Django 5.1.1 on 2025-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo_user",
            field=models.BooleanField(default=False),
        ),
    ]
