# Generated by Django 4.2.11 on 2025-04-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_is_demo_user"),
    ]

    operations = []
