# Generated by Django 4.2.11 on 2025-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20250406_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tweets_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
