name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: twitter_clone_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      
      - name: Configure Poetry
        run: poetry config virtualenvs.create false
      
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install --no-root
      
      - name: Set up environment variables
        working-directory: ./backend
        run: |
          echo "DEBUG=True" >> .env
          echo "SECRET_KEY=test-secret-key-for-ci" >> .env
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/twitter_clone_test" >> .env
          echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
          echo "CORS_ALLOWED_ORIGINS=http://localhost:3000" >> .env
      
      - name: Run migrations
        working-directory: ./backend
        run: poetry run python manage.py migrate
      
      - name: Run tests with coverage
        working-directory: ./backend
        run: poetry run pytest --cov=. --cov-report=xml
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          flags: backend
  
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          rm -f package-lock.json
          npm install
          npm ci
      
      - name: Set up environment variables
        working-directory: ./frontend
        run: |
          echo "REACT_APP_API_URL=http://localhost:8000/api" >> .env
      
      - name: Run linting
        working-directory: ./frontend
        run: npm run lint
      
      - name: Run tests with coverage
        working-directory: ./frontend
        run: npm test -- --coverage --watchAll=false
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./frontend/coverage/coverage-final.json
          flags: frontend
      
      - name: Run Cypress E2E tests
        working-directory: ./frontend
        run: npm run cypress:run
  
  build:
    needs: [backend-tests, frontend-tests]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
      
      - name: Archive frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      
      - name: Configure Poetry
        run: poetry config virtualenvs.create false
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: poetry install --no-dev --no-root
      
      - name: Archive backend app
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: |
            backend/
            !backend/node_modules/
            !backend/.pytest_cache/
            !backend/__pycache__/
  
  deploy-backend:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download backend app
        uses: actions/download-artifact@v3
        with:
          name: backend-app
          path: backend
      
      - name: Deploy to PythonAnywhere
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PYTHONANYWHERE_HOST }}
          username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
          password: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
          script: |
            cd ${{ secrets.PYTHONANYWHERE_PROJECT_PATH }}
            git pull
            source ${{ secrets.PYTHONANYWHERE_VENV_PATH }}/bin/activate
            cd backend
            pip install poetry
            poetry install --no-dev
            python manage.py migrate
            touch ${{ secrets.PYTHONANYWHERE_WSGI_PATH }}
  
  deploy-frontend:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel deploy --prod --token=$VERCEL_TOKEN
  
  deploy-staging:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Deploy to Vercel Preview
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel deploy --token=$VERCEL_TOKEN 